# Generated by Django 5.0.1 on 2024-01-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='text',
            field=models.CharField(default='nash', max_length=100),
            preserve_default=False,
        ),
    ]
